//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public Events()
        {
            this.EventsComments = new HashSet<EventsComments>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public string PhotoName { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<EventsComments> EventsComments { get; set; }
    }
}
